name: Release

on: [push]

jobs:
  build-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: version
        uses: ./.github/actions/version

      - name: Install dependencies
        uses: docker://node:12-alpine
        with:
          args: yarn --pure-lockfile

      - name: Install dependencies
        uses: docker://node:12
        env:
          ASSET_PATH: https://cdn.loalang.xyz/${{ steps.version.outputs.version }}/
        with:
          args: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
            rustup default nightly
            yarn webpack --mode production

#   build-libs:
#     runs-on: ubuntu-latest
